version: '3'

services:
  web:
    container_name: web_app
    build:
      context: ./
      dockerfile: stripy/Dockerfile
    command: bash -c "source start.sh"
    ports:
      - 8000:8000

    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
    ports:
      - '5432'
