version: '3.7'

services:
  web:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=testy_rishat_db

volumes:
  postgres_data: